# Generated by Django 3.0.5 on 2020-09-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='serviceLoc',
            field=models.TextField(blank=True, choices=[['Kochi', 'Kochi'], ['Alappuzha', 'Alappuzha'], ['Palakkad', 'Palakkad']], default=''),
        ),
    ]
