# Generated by Django 3.0.5 on 2020-09-26 22:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_device_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['Food', 'Food'], ['Electronics', 'Electronics'], ['Sports', 'Sports'], ['Clothing', 'Clothing']], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='interested_vendors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['Lulu Hypermarket', 'Lulu Hypermarket']], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='serviceLoc',
            field=models.TextField(blank=True, choices=[['Kochi', 'Kochi'], ['Palakkad', 'Palakkad'], ['Thiruvananthapuram', 'Thiruvananthapuram'], ['Thrissur', 'Thrissur']], default=''),
        ),
    ]
