# Generated by Django 3.0.5 on 2020-09-12 21:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200912_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['Food', 'Food'], ['Outdoor', 'Outdoor'], ['Electronics', 'Electronics'], ['Clothing', 'Clothing'], ['Sports', 'Sports']], default='', max_length=40),
        ),
    ]
