# Generated by Django 3.0.5 on 2020-09-12 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200912_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_gen_time',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_exp_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
