# Generated by Django 3.0.5 on 2020-09-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_is_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='numberOfRedeemableCoins',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='totalActiveDeals',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='totalCollectedDeals',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='totalDeals',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='serviceLoc',
            field=models.TextField(blank=True, choices=[['Kochi', 'Kochi'], ['Alappuzha', 'Alappuzha'], ['Palakkad', 'Palakkad'], ['Kannur', 'Kannur'], ['Thiruvananthapuram', 'Thiruvananthapuram']], default=''),
        ),
    ]
