# Generated by Django 3.0.5 on 2020-10-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200930_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='userCD',
        ),
        migrations.DeleteModel(
            name='Global',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='ServiceLoc',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interested_vendors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_otp_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='no_of_coins',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_exp_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='serviceLoc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userCD',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
