# Generated by Django 3.0.5 on 2020-09-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200914_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
