# Generated by Django 3.1.2 on 2020-10-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201003_0059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_dtl',
        ),
    ]
