# Generated by Django 3.1.2 on 2020-10-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201003_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_dtl',
            old_name='username',
            new_name='name',
        ),
    ]
