# Generated by Django 3.0.5 on 2020-09-21 01:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_user_vendor_is_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interested_vendors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['Lulu Hypermarket', 'Lulu Hypermarket'], ['VKC Footwear', 'VKC Footwear']], default='', max_length=29),
        ),
    ]
