# Generated by Django 3.1.2 on 2020-10-03 02:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201003_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EXP_TIME', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCD', models.CharField(blank=True, max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('gender', models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='')),
                ('dob', models.DateField(null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_exp_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_otp_verified', models.NullBooleanField(default=False)),
                ('interest', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['Food', 'Food'], ['Electronics', 'Electronics'], ['Sports', 'Sports'], ['Clothing', 'Clothing']], default='', max_length=32)),
                ('status', models.TextField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('SUSPENDED', 'SUSPENDED')], default='')),
                ('no_of_coins', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serviceLoc', models.TextField(blank=True, choices=[['Kochi', 'Kochi'], ['Palakkad', 'Palakkad'], ['Thiruvananthapuram', 'Thiruvananthapuram'], ['Thrissur', 'Thrissur']], default='')),
                ('interested_vendors', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['Lulu Hypermarket', 'Lulu Hypermarket']], default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('totalDeals', models.CharField(blank=True, max_length=5)),
                ('totalActiveDeals', models.CharField(blank=True, max_length=5)),
                ('numberOfRedeemableCoins', models.CharField(blank=True, max_length=5)),
                ('totalCollectedDeals', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='User_dtl',
        ),
        migrations.AddField(
            model_name='device',
            name='userCD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
