# Generated by Django 3.1.2 on 2020-10-03 02:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201003_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='interested_vendors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_otp_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='serviceLoc',
            field=models.TextField(blank=True, choices=[], default=''),
        ),
    ]
