# Generated by Django 3.0.5 on 2020-09-24 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200921_0143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceLoc',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
