# Generated by Django 3.0.5 on 2020-09-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200924_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_id', models.IntegerField()),
                ('location', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
