# Generated by Django 3.0.5 on 2020-09-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_serviceloc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('totalDeals', models.CharField(blank=True, max_length=5)),
                ('totalActiveDeals', models.CharField(blank=True, max_length=5)),
                ('numberOfRedeemableCoins', models.CharField(blank=True, max_length=5)),
                ('totalCollectedDeals', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
