# Generated by Django 3.1.2 on 2020-10-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201017_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vendor_is_followed',
            field=models.BooleanField(default=False),
        ),
    ]
