# Generated by Django 3.1.2 on 2020-10-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201017_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yesdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(max_length=500, null=True)),
                ('deal_desc', models.TextField(blank=True)),
                ('deal_org_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deal_spl_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ServiceLoc', models.CharField(blank=True, max_length=100)),
                ('deal_cateogry', models.CharField(blank=True, max_length=100)),
                ('deal_img1', models.ImageField(blank=True, null=True, upload_to='document')),
                ('deal_img2', models.ImageField(blank=True, null=True, upload_to='document')),
                ('deal_img3', models.ImageField(blank=True, null=True, upload_to='document')),
                ('deal_img4', models.ImageField(blank=True, null=True, upload_to='document')),
                ('deal_img5', models.ImageField(blank=True, null=True, upload_to='document')),
                ('deal_start_time', models.DateTimeField(auto_now_add=True)),
                ('deal_end_time', models.DateTimeField(auto_now_add=True)),
                ('deal_count', models.IntegerField(default=0)),
            ],
        ),
    ]
