# Generated by Django 3.0.5 on 2020-09-24 03:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceloc',
            name='loc_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['Food', 'Food'], ['Beauty', 'Beauty'], ['Sports', 'Sports'], ['Electronics', 'Electronics']], default='', max_length=30),
        ),
    ]
