# Generated by Django 3.1.2 on 2020-10-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_yesdeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesdeal',
            name='ServiceLoc',
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_srvc_loc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_vendor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=500)),
                ('branch_street', models.CharField(blank=True, max_length=100)),
                ('branch_city', models.CharField(blank=True, max_length=100)),
                ('brnach_pin', models.CharField(blank=True, max_length=100)),
                ('branch_contact', models.CharField(blank=True, max_length=100)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
        ),
    ]
