# Generated by Django 3.0.5 on 2020-09-26 00:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200924_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='interested_vendors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['Lulu Hypermarket', 'Lulu Hypermarket'], ['VKC Footwear', 'VKC Footwear'], ['Bismi', 'Bismi']], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='serviceLoc',
            field=models.TextField(blank=True, choices=[['Kochi', 'Kochi'], ['Palakkad', 'Palakkad'], ['Kannur', 'Kannur'], ['Thiruvananthapuram', 'Thiruvananthapuram']], default=''),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, size=None)),
                ('device_type', multiselectfield.db.fields.MultiSelectField(choices=[('ANDROID', 'ANDROID'), ('iOS', 'iOS')], max_length=11)),
                ('device_id', models.CharField(blank=True, max_length=20)),
                ('userCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
