# Generated by Django 3.0.5 on 2020-09-26 00:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200926_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ANDROID', 'ANDROID'), ('iOS', 'iOS')], default='', max_length=11),
        ),
    ]
