# Generated by Django 3.1.2 on 2020-10-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_yesdeal_deal_available_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesdeal',
            name='deal_cateogry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interest'),
        ),
    ]
