# Generated by Django 3.0.5 on 2020-09-26 00:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200926_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('ANDROID', 'ANDROID'), ('iOS', 'iOS')], default=''), size=None),
        ),
    ]
