# Generated by Django 3.1.2 on 2020-11-01 06:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201026_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yesdeal',
            old_name='deal_cateogry',
            new_name='deal_category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vendor_is_followed',
        ),
        migrations.AddField(
            model_name='interest',
            name='category_id',
            field=models.IntegerField(default=100, unique=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='category_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(to='app.Interest', verbose_name='user_interest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interested_vendors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='serviceLoc',
            field=models.TextField(blank=True, choices=[], default=''),
        ),
        migrations.AlterField(
            model_name='yesdeal',
            name='deal_org_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='yesdeal',
            name='deal_spl_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('userCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
