# Generated by Django 3.1.2 on 2020-11-02 03:19

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201101_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_vendor_name',
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_offer_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interested_vendors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['Lulu Hypermarket', 'Lulu Hypermarket']], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='serviceLoc',
            field=models.TextField(blank=True, choices=[['Kochi', 'Kochi']], default=''),
        ),
        migrations.AlterField(
            model_name='yesdeal',
            name='deal_spl_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
