# Generated by Django 3.1.2 on 2020-11-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201105_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interested_vendors',
        ),
        migrations.RemoveField(
            model_name='user_deal',
            name='QR_code',
        ),
        migrations.AddField(
            model_name='user_deal',
            name='QRCode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img1',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img2',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img3',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img4',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img5',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_webpage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_QRCode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
