# Generated by Django 3.1.2 on 2020-11-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201106_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='no_of_coins',
        ),
    ]
