# Generated by Django 3.1.2 on 2020-11-09 03:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_user_no_of_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_deal',
            name='QRCode',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_fb_link',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_img1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_img2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_img3',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_img4',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_img5',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_twitter_link',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_webpage',
        ),
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_QRCode',
        ),
        migrations.AddField(
            model_name='user',
            name='interested_vendors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['Lulu Hypermarket', 'Lulu Hypermarket']], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_coins',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='user_deal',
            name='QR_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
