# Generated by Django 3.1.2 on 2020-11-12 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201109_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yesdeal',
            old_name='deal_count',
            new_name='deal_avail_max',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interested_vendors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='no_of_coins',
        ),
        migrations.RemoveField(
            model_name='user_deal',
            name='QR_code',
        ),
        migrations.AddField(
            model_name='user_deal',
            name='QRCode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img1',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img2',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img3',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img4',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img5',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_webpage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_QRCode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='yesdeal',
            name='deal_end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yesdeal',
            name='deal_start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
