# Generated by Django 3.1.2 on 2020-11-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201112_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_deal',
            old_name='deal_id',
            new_name='deal',
        ),
        migrations.RenameField(
            model_name='user_deal',
            old_name='userCD',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_deal',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='interest',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_status',
            field=models.TextField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default=''),
        ),
    ]
