# Generated by Django 3.1.2 on 2020-11-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20201117_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
