# Generated by Django 3.1.2 on 2020-11-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20201126_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service_area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
