# Generated by Django 3.1.2 on 2020-11-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201126_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service_area',
            field=models.TextField(blank=True, choices=[['Kochi', 'Kochi']], default=''),
        ),
    ]
