# Generated by Django 3.1.2 on 2020-11-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201126_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='service_area',
            new_name='serviceLoc',
        ),
    ]
