# Generated by Django 3.1.2 on 2020-11-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20201126_0142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceLoc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='serviceLoc',
        ),
    ]
