# Generated by Django 3.1.2 on 2020-11-26 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20201126_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_srvc_loc',
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_srvc_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.area'),
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_srvc_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region'),
        ),
    ]
