# Generated by Django 3.1.2 on 2020-12-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20201129_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
