# Generated by Django 3.1.2 on 2020-12-04 13:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20201203_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
