# Generated by Django 3.1.2 on 2020-12-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20201204_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_deal',
            name='user_wah_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='location_pin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_collected_till',
            field=models.IntegerField(default=0),
        ),
    ]
