# Generated by Django 3.1.2 on 2020-12-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20201206_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_deal',
            name='deal_scratch_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
