# Generated by Django 3.1.2 on 2020-12-06 04:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_user_deal_deal_scratch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared_coin_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfRedeemableCoins', models.IntegerField(default=0)),
                ('from_user', models.CharField(blank=True, max_length=12, unique=True)),
                ('num_of_shared_coins', models.IntegerField(default=0)),
                ('shared_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('shared_method', models.TextField(blank=True, choices=[('Request', 'Request'), ('Send', 'Send')], default='')),
                ('userCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='sample',
        ),
        migrations.AddField(
            model_name='user_vendor',
            name='user_coins',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.shared_coin_history'),
        ),
    ]
