# Generated by Django 3.1.2 on 2020-12-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_shared_coin_history_vendor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_vendor',
            old_name='user_coins',
            new_name='numberOfRedeemableCoins',
        ),
        migrations.AlterField(
            model_name='shared_coin_history',
            name='numberOfRedeemableCoins',
            field=models.IntegerField(),
        ),
    ]
