# Generated by Django 3.1.2 on 2020-12-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20201211_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_coin_history',
            name='from_user',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
