# Generated by Django 3.1.2 on 2020-12-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20201211_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared_coin_history',
            old_name='userCD',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shared_coin_history',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.AlterField(
            model_name='shared_coin_history',
            name='shared_method',
            field=models.TextField(blank=True, choices=[('Recieved', 'Recieved'), ('Send', 'Send'), ('Compliment', 'Compliment')], default=''),
        ),
    ]
