# Generated by Django 3.1.2 on 2020-12-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20201211_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_coin_history',
            name='num_of_comp_coins',
            field=models.IntegerField(default=0),
        ),
    ]
