# Generated by Django 3.1.2 on 2020-12-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_shared_coin_history_num_of_comp_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_coin_history',
            name='numberOfRedeemableCoins',
            field=models.IntegerField(default=0),
        ),
    ]
