# Generated by Django 3.1.2 on 2020-12-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20201213_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared_coin_history',
            name='from_user',
        ),
    ]
