# Generated by Django 3.1.2 on 2020-12-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_shared_coin_history_from_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_vendor',
            old_name='userCD',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_vendor',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
