# Generated by Django 3.1.2 on 2021-01-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_vendor_vendor_cd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
