# Generated by Django 3.1.2 on 2021-01-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20210127_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='brnach_pin',
            new_name='branch_pin',
        ),
    ]
