# Generated by Django 3.1.2 on 2021-02-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20210127_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='location_pin',
            new_name='vendor_email',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_logo',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_pin_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_whatsapp',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
