# Generated by Django 3.1.2 on 2021-02-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20210201_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='image_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
