# Generated by Django 3.1.2 on 2021-02-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_interest_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor_token', models.CharField(blank=True, max_length=16, null=True)),
                ('vendor_status', models.TextField(blank=True, choices=[('Active', 'Active'), ('Approval Pending', 'Approval Pending'), ('Deactivated', 'Deactivated')], default='')),
            ],
        ),
    ]
