# Generated by Django 3.1.2 on 2021-02-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_vendor_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_login',
            name='vendor_status',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_status',
            field=models.TextField(blank=True, choices=[('Active', 'Active'), ('Approval Pending', 'Approval Pending'), ('Deactivated', 'Deactivated')], default=''),
        ),
    ]
