# Generated by Django 3.1.2 on 2021-02-21 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20210215_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_img2',
        ),
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_img3',
        ),
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_img4',
        ),
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_img5',
        ),
        migrations.AlterField(
            model_name='yesdeal',
            name='deal_img1',
            field=models.ImageField(blank=True, null=True, upload_to='deal'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interest')),
            ],
        ),
    ]
