# Generated by Django 3.1.2 on 2021-02-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20210221_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_img2',
            field=models.ImageField(blank=True, null=True, upload_to='yesdeal/media/vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_img3',
            field=models.ImageField(blank=True, null=True, upload_to='yesdeal/media/vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_img4',
            field=models.ImageField(blank=True, null=True, upload_to='yesdeal/media/vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_img5',
            field=models.ImageField(blank=True, null=True, upload_to='yesdeal/media/vendor'),
        ),
    ]
