# Generated by Django 3.1.2 on 2021-02-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20210221_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('img_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interest')),
            ],
        ),
    ]
