# Generated by Django 3.1.2 on 2021-02-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_deal_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
