# Generated by Django 3.1.2 on 2021-02-27 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20210227_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='yesdeal/media/gallory')),
                ('provider', models.TextField(blank=True, choices=[('VENDOR', 'VENDOR'), ('ADMIN', 'ADMIN')], default='')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
        ),
        migrations.RemoveField(
            model_name='deal_img_vendor',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='deal_img_vendor',
            name='vendor_name',
        ),
        migrations.DeleteModel(
            name='Deal_img_category',
        ),
        migrations.DeleteModel(
            name='Deal_img_vendor',
        ),
    ]
