# Generated by Django 3.1.2 on 2021-02-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20210227_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_img1',
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_img',
            field=models.ImageField(blank=True, null=True, upload_to='yesdeal/media/gallory'),
        ),
    ]
