# Generated by Django 3.1.2 on 2021-02-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20210227_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cd',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='provider',
            field=models.TextField(blank=True, choices=[('Vendor', 'Vendor'), ('Admin', 'Admin')], default=''),
        ),
    ]
