# Generated by Django 3.1.2 on 2021-03-01 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20210228_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
    ]
