# Generated by Django 3.1.2 on 2021-03-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_yesdeal_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='yesdeal',
            name='Alloted_deal_per_coupon',
            field=models.IntegerField(default=0),
        ),
    ]
