# Generated by Django 3.1.2 on 2021-03-02 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_yesdeal_alloted_deal_per_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Deal_Images', 'verbose_name_plural': 'Deal_Images'},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_img1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_img2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_img3',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_img4',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_img5',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_img',
            field=models.ImageField(blank=True, null=True, upload_to='yesdeal/media/gallory'),
        ),
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.interest'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='yesdeal/media/gallory'),
        ),
    ]
