# Generated by Django 3.1.2 on 2021-03-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20210302_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_deal',
            name='is_deal_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
