# Generated by Django 3.1.2 on 2021-03-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_user_deal_is_deal_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_available_branch',
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_available_branch',
            field=models.ManyToManyField(to='app.Branch', verbose_name='vendor_branches'),
        ),
    ]
