# Generated by Django 3.1.2 on 2021-03-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20210309_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_srvc_area',
        ),
        migrations.AddField(
            model_name='yesdeal',
            name='deal_srvc_area',
            field=models.ManyToManyField(to='app.Area', verbose_name='service_area'),
        ),
    ]
