# Generated by Django 3.1.2 on 2021-03-09 03:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_yesdeal_deal_preference'),
    ]

    #operations = [
        #migrations.AlterField(
            #model_name='yesdeal',
            #name='deal_preference',
            #field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, null=True, size=50),
        #),
    #]
