# Generated by Django 3.1.2 on 2021-03-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20210309_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesdeal',
            name='deal_preference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Select deal preference'),
        ),
    ]
