# Generated by Django 3.1.2 on 2021-03-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20210309_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesdeal',
            name='deal_preference',
            field=models.TextField(help_text="It's a good manners to write it", null=True),
        ),
    ]
