# Generated by Django 3.1.2 on 2021-03-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20210309_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_deal',
            name='deal_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
