# Generated by Django 3.1.2 on 2021-03-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_user_deal_deal_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal_scratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scratch_logo', models.ImageField(blank=True, null=True, upload_to='yesdeal/media/logo')),
            ],
        ),
    ]
