# Generated by Django 3.1.2 on 2021-05-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_auto_20210505_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='user_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user_pin_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
