# Generated by Django 3.1.2 on 2021-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_auto_20210505_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_lat',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='user_long',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
