# Generated by Django 3.1.2 on 2021-05-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20210506_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user_lat',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user_long',
        ),
    ]
