# Generated by Django 3.1.2 on 2021-05-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_auto_20210506_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesdeal',
            name='deal_QRCode',
        ),
    ]
