# Generated by Django 3.1.2 on 2021-05-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_yesdeal_deal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesdeal',
            name='deal_preference',
            field=models.TextField(blank=True, help_text="It's a good manners to write it", null=True),
        ),
    ]
