# Generated by Django 3.1.2 on 2021-05-23 04:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_auto_20210518_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('user_comment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='user_deal',
            name='user_review',
            field=models.TextField(blank=True, help_text="It's a good manners to write it", null=True),
        ),
        migrations.AddField(
            model_name='user_deal',
            name='user_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user_feedback'),
        ),
    ]
