# Generated by Django 3.1.2 on 2021-05-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_auto_20210523_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_deal',
            name='rating_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
