# Generated by Django 3.1.2 on 2021-05-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_user_deal_rating_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_deal',
            name='user_rating',
            field=models.CharField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default='', max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='User_Feedback',
        ),
    ]
