# Generated by Django 3.1.2 on 2021-05-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_auto_20210531_0531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Review_Rating',
        ),
    ]
